const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#fff",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
  },
  theme: {
    primaryBackground: "#CBE3E5",
    rentPrimary: "#1F4C6B",
    expressBackground: "#D7F0F2",
    primary: "#64C8CE",
    primaryDark: "#32969C",
    accent: "#F2C773",
    text: "#000",
    googleRed: "#FF3D00",
    onboardingButton: "#f2c773",
    contactTitle: "#50A2A7",
    lightBg: "#F0FEFF",
    primaryGrey: "#555555",
    primaryRed: "#E75480",
    surface: "#Fff",
    light: "white",
    stroke: "#000",
    secondary: "#F2C773",
    primaryOrange: "#E9B44C",
    error: "#FAA0A0",
    danger: "#FAA0A0",
    lightOrange: "#FFFAF0",
    inputBorder: "#EFEFF4",
    success: "#6CD1A1",
    darkGreen: "#8BC83D",
    lightGreen: "#8DFF00",
    mainGrey: "#ECEDF3",
    mainDarkGrey: "#A1A5C1",
    estateGrey: "#F5F4F8",
  },
};
